create database arduino;

 CREATE TABLE registro (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
reg_hash VARCHAR(20) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 